### ISSUE TITLE
ClassFinderTest fails with JRE classes on Java 14 [PAXTB-38]

### ISSUE THREAD

**Issue by ops4j-issues** [ops4j/org.ops4j.pax.tinybundles#45]
**[Oliver Lietz](https://ops4j1.jira.com/secure/ViewProfile.jspa?accountId=557058:a018e4d5-9bbe-4268-9ae9-2c253f8fe872)** created **[PAXTB-38](https://ops4j1.jira.com/browse/PAXTB-38)** 

```
findAllEmbeddedClassesFromJreClass(org.ops4j.pax.tinybundles.core.ClassFinderTest)  Time elapsed: 0.007 sec  <<< ERROR!
java.lang.IllegalArgumentException: No bundle found for class class java.util.regex.Pattern. Unsupported woven or system package classes
	at org.ops4j.pax.tinybundles.finder.ClassFinder.findAllEmbeddedClasses(ClassFinder.java:106)
	at org.ops4j.pax.tinybundles.finder.ClassFinder.findAllEmbeddedClasses(ClassFinder.java:46)
	at org.ops4j.pax.tinybundles.core.ClassFinderTest.findAllEmbeddedClassesFromJreClass(ClassFinderTest.java:101)

findAnonymousClassesFromJreClass(org.ops4j.pax.tinybundles.core.ClassFinderTest)  Time elapsed: 0.001 sec  <<< ERROR!
java.lang.IllegalArgumentException: No bundle found for class class java.util.regex.Pattern. Unsupported woven or system package classes
	at org.ops4j.pax.tinybundles.finder.ClassFinder.findAllEmbeddedClasses(ClassFinder.java:106)
	at org.ops4j.pax.tinybundles.finder.ClassFinder.findAnonymousClasses(ClassFinder.java:52)
	at org.ops4j.pax.tinybundles.core.ClassFinderTest.findAnonymousClassesFromJreClass(ClassFinderTest.java:112)
```

---

Votes: 0, Watches: 1

**Comment by oliverlietz** [comment]
Fixed by #50
